# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 16:37
from __future__ import unicode_literals

from django.db import migrations
from fw_auth.models import GlobalPermission

new_permissions = [
    ('Create Object1', 'global.object_1.add'),
    ('Delete Object1', 'global.object_1.delete'),
    ('Change Object1', 'global.object_1.change'),
    ('Reset settings', 'global.reset_settings'),
]

def createPermissions(apps, schema_editor):
    for p in new_permissions:
        GlobalPermission.objects.create(name=p[0], codename=p[1])


def deletePremissions(app, schema_editor):
    for p in new_permissions:
        GlobalPermission.objects.filter(codename=p[1]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fw_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(createPermissions, deletePremissions)
    ]
