jobs:
  build_frontend:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "build frontend"
  test_frontend:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "test frontend"
workflows:
  version: 2
  build_and_test_frontend:
    jobs:
      - build_frontend
      - test_frontend
        requires:
        - build_frontend
