jobs:
  checkout:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - run: echo "start building"
      - run: echo "stop buiding"
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - run: echo "start testing"
      - run: echo "stop testing"
      
workflows:
  version: 2
  jobs:
    - checkout
    - build:
        requires:
          - checkout
    - test:
        requires:
          - build
