jobs:
  build_frontend:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "build frontend"
  test_frontend:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "test frontend"
  test_backend:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run: echo "test backend"
  deploy:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run: echo "deploy"
workflows:
  version: 2
  build_and_test_frontend:
    jobs:
      - test_backend
      - build_frontend
      - test_frontend:
          requires:
            - build_frontend
      - deploy:
          requires:
            - test_backend
            - test_frontend
       
